version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-ui:
    image: redislabs/redisinsight:latest
    container_name: redis-ui
    ports:
      - "8001:8001"
    networks:
      - redis-network
    environment:
      - REDISINSIGHT_HOST=0.0.0.0
    depends_on:
      - redis

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data:
